import {
  TERMINAL_COMMANDS,
  INTRO,
  INSTRUCTIONS_PT_ONE,
  INSTRUCTIONS_PT_TWO,
  INSTRUCTIONS_PT_TWO_MOBILE,
} from "./homeConstants";

export {
  TERMINAL_COMMANDS,
  INTRO,
  INSTRUCTIONS_PT_ONE,
  INSTRUCTIONS_PT_TWO,
  INSTRUCTIONS_PT_TWO_MOBILE,
};
